stages:
  - build
  - publish

## Templates
.runners: &runners
  tags:
    - private
    - docker
    - kubernetes
    - amd64

.publish_container_image: &publish_container_image
  <<: *runners
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - REGISTRY_AUTH=$(echo -n ${REGISTRY_USER}:${REGISTRY_PASSWORD} | base64)
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"${REGISTRY_AUTH}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile ${CI_PROJECT_DIR}/${CONTAINER_DOCKERFILE:-Dockerfile}
      --destination ${CONTAINER_IMAGE_NAME}
      ${KANIKO_EXTRA_ARG}

.github_release: &github_release
  <<: *runners
  image:
    name: angelbarrera92/plugins-github-release:latest
    entrypoint: [""]
  script:
    - /bin/drone-github-release
      --api-key "${GITHUB_RELEASE_GITHUB_ACCESS_TOKEN}"
      --prerelease="${GITHUB_RELEASE_IS_PRE_RELEASE}"
      --repo.name="${GITHUB_RELEASE_REPOSITORY_NAME}"
      --repo.owner="${GITHUB_RELEASE_REPOSITORY_OWNER}"
      --overwrite
      --build.event="tag"
      --title="${GITHUB_RELEASE_TITLE}"
      --commit.ref="${CI_COMMIT_TAG}"
      --files "${GITHUB_RELEASE_FILES}"

build:
  stage: build
  <<: *runners
  image: golang:1.21.5
  before_script:
    - go mod download
    - mkdir binaries
  script:
    - cd cmd/loki-multi-tenant-proxy
    - GOOS=darwin GOARCH=amd64 go build -o loki-multi-tenant-proxy -ldflags="-X 'main.version=${CI_COMMIT_TAG:-${CI_COMMIT_SHORT_SHA}}' -X 'main.commit=${CI_COMMIT_SHORT_SHA}'"
    - mv loki-multi-tenant-proxy ../../binaries/loki-multi-tenant-proxy-darwing-amd64
    - GOOS=linux GOARCH=amd64 go build -o loki-multi-tenant-proxy -ldflags="-X 'main.version=${CI_COMMIT_TAG:-${CI_COMMIT_SHORT_SHA}}' -X 'main.commit=${CI_COMMIT_SHORT_SHA}'"
    - mv loki-multi-tenant-proxy ../../binaries/loki-multi-tenant-proxy-linux-amd64
  artifacts:
    paths:
      - binaries/

## Gitlab: builds every commit publishing the container image in the gitlab registry
gitlab_unstable:
  stage: publish
  <<: *publish_container_image
  variables:
    REGISTRY: ${CI_REGISTRY}
    REGISTRY_USER: ${CI_REGISTRY_USER}
    REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}
    CONTAINER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    CONTAINER_DOCKERFILE: build/package/Dockerfile
    KANIKO_EXTRA_ARG: "--build-arg VERSION=${CI_COMMIT_SHORT_SHA} --build-arg COMMIT=${CI_COMMIT_SHORT_SHA}"
  except:
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+)-rc([0-9]+)$/
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/

## Dockerhub: publish the image if is a release candidate or a final release
dockerhub_release_cadidate:
  stage: publish
  <<: *publish_container_image
  variables:
    REGISTRY: ${DOCKERHUB_REGISTRY}
    REGISTRY_USER: ${DOCKERHUB_REGISTRY_USER}
    REGISTRY_PASSWORD: ${DOCKERHUB_REGISTRY_PASSWORD}
    CONTAINER_IMAGE_NAME: ${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    CONTAINER_DOCKERFILE: build/package/Dockerfile
    KANIKO_EXTRA_ARG: "--build-arg VERSION=${CI_COMMIT_TAG} --build-arg COMMIT=${CI_COMMIT_SHORT_SHA}"
  only:
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+)-rc([0-9]+)$/

dockerhub_stable:
  stage: publish
  <<: *publish_container_image
  variables:
    REGISTRY: ${DOCKERHUB_REGISTRY}
    REGISTRY_USER: ${DOCKERHUB_REGISTRY_USER}
    REGISTRY_PASSWORD: ${DOCKERHUB_REGISTRY_PASSWORD}
    CONTAINER_IMAGE_NAME: ${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    CONTAINER_DOCKERFILE: build/package/Dockerfile
    KANIKO_EXTRA_ARG: "--destination ${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:latest --build-arg VERSION=${CI_COMMIT_TAG} --build-arg COMMIT=${CI_COMMIT_SHORT_SHA}"
  only:
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/

## Github: Releases only on release candidate or final release
github_release_candidate:
  <<: *github_release
  stage: publish
  variables:
    GITHUB_RELEASE_IS_PRE_RELEASE: "true"
    GITHUB_RELEASE_REPOSITORY_OWNER: "k8spin"
    GITHUB_RELEASE_REPOSITORY_NAME: "loki-multi-tenant-proxy"
    GITHUB_RELEASE_TITLE: "Release candidate ${CI_COMMIT_TAG}"
    GITHUB_RELEASE_GITHUB_ACCESS_TOKEN: ${GITHUB_TOKEN}
    GITHUB_RELEASE_FILES: "binaries/loki-multi-tenant-proxy-darwing-amd64,binaries/loki-multi-tenant-proxy-linux-amd64"
  only:
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+)-rc([0-9]+)$/

github_release:
  <<: *github_release
  stage: publish
  variables:
    GITHUB_RELEASE_IS_PRE_RELEASE: "false"
    GITHUB_RELEASE_REPOSITORY_OWNER: "k8spin"
    GITHUB_RELEASE_REPOSITORY_NAME: "loki-multi-tenant-proxy"
    GITHUB_RELEASE_TITLE: "Release ${CI_COMMIT_TAG}"
    GITHUB_RELEASE_GITHUB_ACCESS_TOKEN: ${GITHUB_TOKEN}
    GITHUB_RELEASE_FILES: "binaries/loki-multi-tenant-proxy-darwing-amd64,binaries/loki-multi-tenant-proxy-linux-amd64"
  only:
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/
